server:
  address: server:5000

log:
  level: INFO

data:
  dir: /data

batch:
  maxAmount: 100

protocol:
  fieldSeparator: ";"
  batchSeparator: "~"
  messageDelimiter: "\n"
  finishedHeader: "F:"
  successBody: "OK"
  failureBody: "FAIL"
  finishedBody: "FINISHED"