name: tp-distribuidos-grupo13
services:
  filter_year:
    build:
      context: .          
      dockerfile: workers/filter/Dockerfile
    container_name: filter_service
    command: ["python", "main.py", "--filter", "year"]
    volumes:
      - ./workers/filter/config_year.ini:/workers/filter/config_year.ini
      - ./utils:/utils:ro
      - ./middleware:/middleware:ro

    networks: [testing_net] 

networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
