name: tp-distribuidos-grupo13
services:
  server:
    container_name: server
    image: server:latest
    entrypoint: ["python3", "/main.py"]
    environment:
      - PYTHONUNBUFFERED=1
      - CLI_CLIENTS=1
    networks: [testing_net]
    volumes:
      - ./server/config.ini:/config.ini:ro
  client1:
    container_name: client1
    image: client:latest
    # NO sobreescribas entrypoint: lo define el Dockerfile como ["python3","/client/main.py"]
    # Si quisieras explicitarlo, sería:
    # entrypoint: ["python3","/client/main.py"]
    environment:
      - CLI_ID=1
      - CLI_DATA_DIR=/data
      - DATA_MODE=tree
    networks: [testing_net]
    depends_on: [server]
    volumes:
      - ./.data/client-1:/data:ro
      - ./client/config.yaml:/config.yaml:ro
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
