name: tp-distribuidos-grupo13
services:
  server:
    container_name: server
    build:
      context: .             # project root
      dockerfile: server/Dockerfile
    entrypoint: ["python3", "main.py"]
    environment:
      - PYTHONUNBUFFERED=1
      - CLI_CLIENTS=1
    networks: [testing_net]
    volumes:
      - ./server/config.ini:/config.ini:ro
      - ./utils:/server/utils:ro
  client:
    container_name: client1
    build:
      context: .             # project root
      dockerfile: client/Dockerfile
    entrypoint: ["python3", "main.py"]
    environment:
      - CLI_ID=1
      - CLI_DATA_DIR=/data
      - DATA_MODE=tree
      - SERVER_ADDRESS=server:12345
    networks: [testing_net]
    depends_on:
      server:
        condition: service_started
    volumes:
      - ./utils/communication/tests/test_data:/data:ro
      - ./client/config.ini:/config.ini:ro
      - ./utils:/client/utils:ro
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
