name: tp-distribuidos-grupo13
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
    - 5672:5672
    - 15672:15672
    healthcheck:
      test: [CMD, rabbitmqctl, status]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
    - testing_net
  client-1:
    build:
      context: .
      dockerfile: client/Dockerfile
    entrypoint: [python3, main.py]
    container_name: client-1
    environment:
    - CLI_ID=1
    - CLI_DATA_DIR=/data
    - CLI_OUTPUT_DIR=/output
    - DATA_MODE=tree
    - SERVER_ADDRESS=server:12345
    volumes:
    - ./.data-reduced:/data:ro
    - ./.results/client-1:/output
    - ./client/config.ini:/config.ini:ro
    - ./utils:/client/utils:ro
    - ./middleware:/client/middleware:ro
    networks:
    - testing_net
    depends_on:
      server:
        condition: service_started
  filter_year_service:
    build:
      context: .
      dockerfile: workers/filter/Dockerfile
    entrypoint: [python3, main.py, --filter, year]
    container_name: filter_year_service
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    volumes:
    - ./workers/filter/config/config_year.ini:/workers/filter/config/config_year.ini:ro
    - ./utils:/workers/utils:ro
    - ./middleware:/workers/middleware:ro
    networks:
    - testing_net
    depends_on:
      server:
        condition: service_started
      rabbitmq:
        condition: service_healthy
  filter_hour_service:
    build:
      context: .
      dockerfile: workers/filter/Dockerfile
    entrypoint: [python3, main.py, --filter, hour]
    container_name: filter_hour_service
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    volumes:
    - ./workers/filter/config/config_hour.ini:/workers/filter/config/config_hour.ini:ro
    - ./utils:/workers/utils:ro
    - ./middleware:/workers/middleware:ro
    networks:
    - testing_net
    depends_on:
      server:
        condition: service_started
      rabbitmq:
        condition: service_healthy
  filter_amount_service:
    build:
      context: .
      dockerfile: workers/filter/Dockerfile
    entrypoint: [python3, main.py, --filter, amount]
    container_name: filter_amount_service
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    volumes:
    - ./workers/filter/config/config_amount.ini:/workers/filter/config/config_amount.ini:ro
    - ./utils:/workers/utils:ro
    - ./middleware:/workers/middleware:ro
    networks:
    - testing_net
    depends_on:
      server:
        condition: service_started
      rabbitmq:
        condition: service_healthy
  server:
    container_name: server
    build:
      context: .
      dockerfile: server/Dockerfile
    entrypoint: [python3, main.py]
    environment:
    - PYTHONUNBUFFERED=1
    - CLI_CLIENTS=1
    volumes:
    - ./server/config.ini:/config.ini:ro
    - ./utils:/server/utils:ro
    - ./middleware:/server/middleware:ro
    networks:
    - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy
networks:
  testing_net:
    driver: bridge
