name: tp-distribuidos-grupo13
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
    - 5672:5672
    - 15672:15672
    healthcheck:
      test: [CMD, rabbitmqctl, status]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
    - testing_net
  client-1:
    build:
      context: .
      dockerfile: client/Dockerfile
    entrypoint: [python3, main.py]
    container_name: client-1
    environment:
    - CLI_ID=1
    - CLI_DATA_DIR=/data
    - CLI_OUTPUT_DIR=/output
    - DATA_MODE=tree
    - SERVER_ADDRESS=server:12345
    volumes:
    - ./.data-test:/data:ro
    - ./.results/client-1:/output
    - ./client/config.ini:/config.ini:ro
    - ./utils:/client/utils:ro
    - ./middleware:/client/middleware:ro
    networks:
    - testing_net
    depends_on:
      server:
        condition: service_started
  filter_year_service:
    build:
      context: .
      dockerfile: workers/filter/Dockerfile
    entrypoint: [python3, main.py, --filter, year]
    container_name: filter_year_service
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=INFO
    volumes:
    - ./workers/filter/config/config_year.ini:/workers/filter/config/config_year.ini:ro
    - ./utils:/workers/utils:ro
    - ./middleware:/workers/middleware:ro
    networks:
    - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy
  aggregator_purchases_service:
    build:
      context: .
      dockerfile: workers/aggregators/Dockerfile
    entrypoint: [python3, main.py]
    container_name: aggregator_purchases_service
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    - AGGREGATOR_TYPE=PURCHASES
    volumes:
    - ./utils:/workers/utils:ro
    - ./middleware:/workers/middleware:ro
    networks:
    - testing_net
    depends_on:
      server:
        condition: service_started
      rabbitmq:
        condition: service_healthy
  maximizer_top3_1_service:
    build:
      context: .
      dockerfile: workers/maximizers/Dockerfile
    entrypoint: [python3, main.py]
    container_name: maximizer_top3_1_service
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    - MAXIMIZER_TYPE=TOP3
    - MAXIMIZER_RANGE=1
    volumes:
    - ./utils:/workers/utils:ro
    - ./middleware:/workers/middleware:ro
    networks:
    - testing_net
    depends_on:
      server:
        condition: service_started
      rabbitmq:
        condition: service_healthy
  maximizer_top3_4_service:
    build:
      context: .
      dockerfile: workers/maximizers/Dockerfile
    entrypoint: [python3, main.py]
    container_name: maximizer_top3_4_service
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    - MAXIMIZER_TYPE=TOP3
    - MAXIMIZER_RANGE=4
    volumes:
    - ./utils:/workers/utils:ro
    - ./middleware:/workers/middleware:ro
    networks:
    - testing_net
    depends_on:
      server:
        condition: service_started
      rabbitmq:
        condition: service_healthy
  aggregator_purchases_service:
    build:
      context: .
      dockerfile: workers/aggregators/Dockerfile
    entrypoint: [python3, main.py]
    container_name: aggregator_purchases_service
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    - AGGREGATOR_TYPE=PURCHASES
    volumes:
    - ./utils:/workers/utils:ro
    - ./middleware:/workers/middleware:ro
    networks:
    - testing_net
    depends_on:
      server:
        condition: service_started
      rabbitmq:
        condition: service_healthy
  maximizer_top3_1_service:
    build:
      context: .
      dockerfile: workers/maximizers/Dockerfile
    entrypoint: [python3, main.py]
    container_name: maximizer_top3_1_service
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    - MAXIMIZER_TYPE=TOP3
    - MAXIMIZER_RANGE=1
    volumes:
    - ./utils:/workers/utils:ro
    - ./middleware:/workers/middleware:ro
    networks:
    - testing_net
    depends_on:
      server:
        condition: service_started
      rabbitmq:
        condition: service_healthy
  maximizer_top3_4_service:
    build:
      context: .
      dockerfile: workers/maximizers/Dockerfile
    entrypoint: [python3, main.py]
    container_name: maximizer_top3_4_service
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    - MAXIMIZER_TYPE=TOP3
    - MAXIMIZER_RANGE=4
    volumes:
    - ./utils:/workers/utils:ro
    - ./middleware:/workers/middleware:ro
    networks:
    - testing_net
    depends_on:
      server:
        condition: service_started
      rabbitmq:
        condition: service_healthy
  maximizer_top3_7_service:
    build:
      context: .
      dockerfile: workers/maximizers/Dockerfile
    entrypoint: [python3, main.py]
    container_name: maximizer_top3_7_service
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    - MAXIMIZER_TYPE=TOP3
    - MAXIMIZER_RANGE=7
    volumes:
    - ./utils:/workers/utils:ro
    - ./middleware:/workers/middleware:ro
    networks:
    - testing_net
    depends_on:
      server:
        condition: service_started
      rabbitmq:
        condition: service_healthy
  maximizer_top3_absolute_service:
    build:
      context: .
      dockerfile: workers/maximizers/Dockerfile
    entrypoint: [python3, main.py]
    container_name: maximizer_top3_absolute_service
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    - MAXIMIZER_TYPE=TOP3
    - MAXIMIZER_RANGE=0
    volumes:
    - ./utils:/workers/utils:ro
    - ./middleware:/workers/middleware:ro
    networks:
    - testing_net
    depends_on:
      server:
        condition: service_started
      rabbitmq:
        condition: service_healthy
  joiner_stores_top3_service:
    build:
      context: .
      dockerfile: workers/joiners/Dockerfile
    entrypoint: [python3, main.py]
    container_name: joiner_stores_top3_service
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    - JOINER_TYPE=STORES_TOP3
    volumes:
    - ./utils:/workers/utils:ro
    - ./middleware:/workers/middleware:ro
    networks:
    - testing_net
    depends_on:
      server:
        condition: service_started
      rabbitmq:
        condition: service_healthy
  joiner_users_service:
    build:
      context: .
      dockerfile: workers/joiners/Dockerfile
    entrypoint: [python3, main.py]
    container_name: joiner_users_service
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    - JOINER_TYPE=USERS
    volumes:
    - ./utils:/workers/utils:ro
    - ./middleware:/workers/middleware:ro
    networks:
    - testing_net
    depends_on:
      server:
        condition: service_started
      rabbitmq:
        condition: service_healthy
  joiner_stores_top3_service:
    build:
      context: .
      dockerfile: workers/joiners/Dockerfile
    entrypoint: [python3, main.py]
    container_name: joiner_stores_top3_service
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    volumes:
    - ./utils:/workers/utils:ro
    - ./middleware:/workers/middleware:ro
    networks:
    - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy
  joiner_users_service:
    build:
      context: .
      dockerfile: workers/joiners/Dockerfile
    entrypoint: [python3, main.py]
    container_name: joiner_users_service
    environment:
    - PYTHONUNBUFFERED=1
    - LOGGING_LEVEL=DEBUG
    volumes:
    - ./utils:/workers/utils:ro
    - ./middleware:/workers/middleware:ro
    networks:
    - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy
  server:
    container_name: server
    build:
      context: .
      dockerfile: server/Dockerfile
    entrypoint: [python3, main.py]
    environment:
    - PYTHONUNBUFFERED=1
    - CLI_CLIENTS=1
    volumes:
    - ./server/config.ini:/config.ini:ro
    - ./utils:/server/utils:ro
    - ./middleware:/server/middleware:ro
    networks:
    - testing_net
    depends_on:
      rabbitmq:
        condition: service_healthy
      filter_year_service:
        condition: service_started
      filter_hour_service:
        condition: service_started
      filter_amount_service:
        condition: service_started

networks:
  testing_net:
    driver: bridge
