name: tp-distribuidos-grupo13
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 5s
      timeout: 5s
      retries: 10
    networks:
      - testing_net

  server:
    container_name: server
    build:
      context: .             
      dockerfile: server/Dockerfile
    entrypoint: ["python3", "main.py"]
    environment:
      - PYTHONUNBUFFERED=1
      - CLI_CLIENTS=1
    networks:
      - testing_net
    volumes:
      - ./server/config.ini:/config.ini:ro
      - ./utils:/server/utils:ro
      - ./middleware:/server/middleware:ro
    depends_on:
      rabbitmq:
        condition: service_healthy
  # -------------------------
  # FILTERS
  # -------------------------
  filter_year:
    build:
      context: .   
      dockerfile: workers/filter/Dockerfile
    container_name: filter_year_service
    command: ["python", "main.py", "--filter", "year"]
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
    volumes:
      - ./workers/filter/config/config_year.ini:/workers/filter/config/config_year.ini
      - ./utils:/workers/utils:ro
      - ./middleware:/workers/middleware:ro
    networks:
      - testing_net
    depends_on:
      server:
        condition: service_started
 
  filter_hour:
    build:
      context: .   
      dockerfile: workers/filter/Dockerfile
    container_name: filter_hour_service
    command: ["python", "main.py", "--filter", "hour"]
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
    volumes:
      - ./workers/filter/config/config_hour.ini:/workers/filter/config/config_hour.ini
      - ./utils:/workers/utils:ro
      - ./middleware:/workers/middleware:ro
    networks:
      - testing_net
    depends_on:
      server:
        condition: service_started

  filter_amount:
    build:
      context: .   
      dockerfile: workers/filter/Dockerfile
    container_name: filter_amount_service
    command: ["python", "main.py", "--filter", "amount"]
    environment:
      - PYTHONUNBUFFERED=1
      - LOGGING_LEVEL=INFO
    volumes:
      - ./workers/filter/config/config_amount.ini:/workers/filter/config/config_amount.ini
      - ./utils:/workers/utils:ro
      - ./middleware:/workers/middleware:ro
    networks:
      - testing_net
    depends_on:
      server:
        condition: service_started
    
  client1:
    container_name: client1
    build:
      context: .             # project root
      dockerfile: client/Dockerfile
    environment:
      - CLI_ID=1
      - CLI_DATA_DIR=/data
      - DATA_MODE=tree
      - SERVER_ADDRESS=server:12345
    networks:
      - testing_net
    depends_on:
      server:
        condition: service_started
    volumes:
      - ./.data/:/data:ro
      - ./client/config.ini:/config.ini:ro
      - ./utils:/client/utils:ro
      - ./middleware:/client/middleware:ro
    
networks:
  testing_net:
    ipam:
      driver: default
      config:
        - subnet: 172.25.125.0/24
